### PR TITLE
 Should this have been several commits? Yes.

### PR DESCRIPTION
**Pull request by ezeiger92**
Well I started off fixing a few more bugs and then accidentally ended up touching about every file in the project. Whoops.

The largest change for users is the change to sample spawning. Using random as part of the loop condition caused very odd distributions when placing multiple samples.
Example: Result of trying to place 3 samples
```
25% no samples
38% 1 sample
28% 2 samples
9% 3 samples
```
Now each sample is given a chance of spawning defined by the config

From the commit message:

> Large rewrite of sections of code
> ~~Fixed ore samples being able to generate with a single ore block~~ Misread code, this message is wrong
> Fixed +8, +8 offset in sample spawning
> Added config option "oreSampleChance", which is the chance any given ore sample will spawn
> Use translated ore names in sample name to provide basic language support
> Samples now break when the block below is broken and when pushed by a piston (Valerate/SimpleOreSamples#6)
> Samples can be broken without a tool
> Samples can replace some surface blocks (tall grass, snow) when spawning
> Sample collision hitbox removed
> Allow any sort of oredict prefix used as a drop to form an item (ie "dustTiny" tries to match "dustTinyIron")

### CODE REVIEW

**Comment by Valerate** [comment]
Oh boy oh boy haha 💯 
I havnt been working on this mod for months and I dont really know too much Java and it seems you have been doing some cleaning up :D
 I wont have time to propertly test this myself due to exams and school, but I assume you have done rigorous testing? And with changes like these I assume its not compatible with old version?

**Comment by ezeiger92** [comment]
Nothing about the block ids have changed, so it should all work with saves from older versions. The only noticeable difference would be the number of samples generating in new chunks and the changes to block properties, which apply to all samples (new and old)

I've done some sanity testing, but I can do more over the weekend. Some friends and I are working on a modpack using this mod, so if there are issues remaining, we'll probably run into them.

**Comment by ezeiger92** [comment]
We haven't run into any issues on client or server, and samples interact as expected with jei, oneprobe, and waila. Our existing config had no issues with these changes and there were no issues with block ids. I'd say that it's pretty stable :)

**Comment by ezeiger92** [comment]
Just checking back in, is there anything more you want tested or changed in this pull?

**Pull request merged**
